### ISSUE TITLE
Simperium 2.0 Release

### ISSUE THREAD

**Issue by jleandroperez** [Simperium/simperium-ios#442]
For simplicity reasons, i'm wrapping up a list of legacy issues into a single list of features for the Simperium 2.0 release.

- [ ] Issue #8: Implement Binary Sync
- [ ] Issue #187: Document Binary Sync API
- [ ] Issue #14: Add support for Mandatory Relationships
- [ ] Issue #40: Allow Sync'ing without CoreData: Make SPJsonStorage production-ready
- [ ] Issue #45: Support Document Based Apps
- [ ] Issue #136: Sync Status Callbacks: Inform the number of objects yet to be sync'ed.
- [ ] Issue #149: Add userInfo field to SPUser, and sync it via Simperium
- [ ] Issue #150: Support Instance-Level Sync'ing
- [ ] Issue #200: Simplify Core Data setup
